### ISSUE TITLE
no menu item

### ISSUE THREAD

**Issue by mcnesium** [danielbrodin/atom-project-manager#139] opened 2015-09-01 13:33 UTC
After upgrade to v2.1.0 the menu item is gone, even after Atom (v1.0.7/OSX) restart it does not reappear. The cmd-ctrl-p project selector does work, though.

**Comment by JSn1nj4** [comment] 2015-09-01 13:59
Exact same as above.

- Windows 10
- Atom 1.0.8.

**Comment by JSn1nj4** [comment] 2015-09-01 14:02
Duplicate of issue #137.

**Closed** 2015-09-01 15:34 UTC
