### ISSUE TITLE
Feature request: open project through command line

### ISSUE THREAD

**Issue by qimingweng** [danielbrodin/atom-project-manager#171] opened 2015-11-28 21:17 UTC
Hi,

I'm not too familiar with Atom's API so this may be impossible, but we can open a folder in atom through the terminal with `atom [directory]`, I wonder if it would be possible to achieve a similar syntax but open these predefined projects instead.

Thanks!

**Comment by lastpotato** [comment] 2016-03-20 02:20
+1

**Comment by dkerzig** [comment] 2016-06-17 14:14
Seems like a duplicate of https://github.com/danielbrodin/atom-project-manager/issues/130

**Comment by qimingweng** [comment] 2016-06-17 14:53
@dkerzig you're right, closing because duplicate of #130

**Closed** 2019-09-19 14:37 UTC
