### ISSUE TITLE
Multiple Root Folders if Multiple Folders in the .cson config

### ISSUE THREAD

**Issue by bnb** [danielbrodin/atom-project-manager#91] opened 2015-03-01 19:30 UTC
Atom added the multiple root features a while ago, and it would be really great if it could be implemented in Project Manager. What I'd like to see is that when you have multiple directories assigned to a project, they all get opened as root folders.

Thanks.

**Comment by ddliu** [comment] 2015-03-02 03:04
Duplicate of #87

**Closed** 2015-03-03 16:03 UTC
