### ISSUE TITLE
ctrl-d after changing projects selects multiple occurences

### ISSUE THREAD

**Issue by omeryagmurlu** [danielbrodin/atom-project-manager#356] opened 2017-08-03 17:11 UTC
Here is a gif explaining the problem
![gif](https://user-images.githubusercontent.com/8201544/28933958-c9d5c46c-7887-11e7-99ae-a40a6d5e4b57.gif)

**Comment by OmeGak** [comment] 2017-08-10 10:07
I think this is a duplicate of #339. The diagnosis (and gif), though, is more accurate.

**Closed** 2019-09-19 14:39 UTC
