### ISSUE TITLE
Failed to activate the project-manager package: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Arcesilas** [danielbrodin/atom-project-manager#224] opened 2016-05-06 13:18 UTC
The problem happened once, but not at Atom restart...

**Atom Version**: 1.7.3
**System**: Ubuntu 15.10
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.9.7
### Stack Trace

Failed to activate the project-manager package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at /home/olivier/.atom/packages/project-manager/lib/projects.js:27:7
    at /home/olivier/.atom/packages/project-manager/lib/cson-db.js:67:9
    at CSONDB.readFile (/home/olivier/.atom/packages/project-manager/lib/cson-db.js:229:7)
    at CSONDB.find (/home/olivier/.atom/packages/project-manager/lib/cson-db.js:35:10)
    at Projects.getAll (/home/olivier/.atom/packages/project-manager/lib/projects.js:22:8)
    at Projects.getCurrent (/home/olivier/.atom/packages/project-manager/lib/projects.js:32:10)
    at Function.updatePaths (/home/olivier/.atom/packages/project-manager/lib/project-manager.js:51:19)
    at /home/olivier/.atom/packages/project-manager/lib/project-manager.js:37:46
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.removePath (/usr/share/atom/resources/app.asar/src/project.js:289:22)
    at Project.updateProps (/home/olivier/.atom/packages/project-manager/lib/project.js:73:24)
    at new Project (/home/olivier/.atom/packages/project-manager/lib/project.js:16:10)
    at Projects.addProject (/home/olivier/.atom/packages/project-manager/lib/projects.js:53:26)
    at /home/olivier/.atom/packages/project-manager/lib/projects.js:24:14
    at /home/olivier/.atom/packages/project-manager/lib/cson-db.js:67:9
    at CSONDB.readFile (/home/olivier/.atom/packages/project-manager/lib/cson-db.js:229:7)
    at CSONDB.find (/home/olivier/.atom/packages/project-manager/lib/cson-db.js:35:10)
    at Projects.getAll (/home/olivier/.atom/packages/project-manager/lib/projects.js:22:8)
    at Projects.getCurrent (/home/olivier/.atom/packages/project-manager/lib/projects.js:32:10)
    at Function.updatePaths (/home/olivier/.atom/packages/project-manager/lib/project-manager.js:51:19)
    at /home/olivier/.atom/packages/project-manager/lib/project-manager.js:37:46
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:263:29)
    at Project.updateProps (/home/olivier/.atom/packages/project-manager/lib/project.js:66:24)
    at new Project (/home/olivier/.atom/packages/project-manager/lib/project.js:16:10)
    at Projects.addProject (/home/olivier/.atom/packages/project-manager/lib/projects.js:53:26)
    at /home/olivier/.atom/packages/project-manager/lib/projects.js:24:14
    at /home/olivier/.atom/packages/project-manager/lib/cson-db.js:67:9
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "disabledPackages": [
      "metrics",
      "spell-check",
      "atom-local-export",
      "symbols-view",
      "php-extract-method",
      "php-debug",
      "php-cs-fixer",
      "file-watcher",
      "blade-snippets",
      "git-plus",
      "language-blade",
      "laravel",
      "merge-conflicts",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-mustache",
      "language-c",
      "language-clojure",
      "language-gfm",
      "markdown-preview",
      "linter-twig",
      "php-integrator-tooltips"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "project-manager": {}
}
```
### Installed Packages

``` coffee
# User
aligner, v0.22.0
aligner-php, v1.0.0
autocomplete-php, v0.3.7
docblockr, v0.7.3
imdone-atom, v1.3.29
language-ini, v1.16.0
language-markdown, v0.13.0
language-todo-extra-words, v0.2.0
linter, v1.11.4
linter-php, v1.2.0
markdown-preview-plus, v2.4.0
markdown-scroll-sync, v2.1.2
node_modules, vundefined
php-integrator-annotations, v0.4.1
php-integrator-autocomplete-plus, v0.8.0
php-integrator-base, v0.9.2
php-integrator-navigation, v0.7.0
php-integrator-symbol-viewer, v0.6.1
php-twig, v4.0.0
project-manager, v2.9.7
symbols-tree-view, v0.12.0
tree-view, v0.205.0

# Dev
No dev packages
```

**Comment by JustinAiken** [comment] 2016-05-06 21:47
Just got the same error when opening a project through the palette - afterwords, my projects.cson is toast :/

**Comment by JustinAiken** [comment] 2016-05-06 22:33
Haha, I'm currently poking around the atom dev console desperately trying to figure out how to save my in-memory `this.db` to the file

**Comment by JustinAiken** [comment] 2016-05-06 23:02
..in case anyone else loses their db to this:

If you still have it loaded in memory in one of your windows (doing `Project Manager: List Projects` works), you can recover your projects!

```javascript
// Open dev tools (alt-apple-i)
pm = require('~/.atom/packages/project-manager/lib/project-manager')
for (  i = 0; i < pm.projects['projects'].length; i++) { pm.projects['projects'][i].save() }
```

**Comment by darylknight** [comment] 2016-06-13 11:01
Shame I didn't see this earlier. my whole projects file just got wiped and I tried to fix it by closing an reopening Atom. Fail.

**Comment by ramirezd42** [comment] 2016-06-20 20:40
This just started happening to me. Projects.cson is just empty braces. Any updates on this?

**Comment by kachkaev** [comment] 2016-06-22 23:20
Also started getting this error a few days bag and a few hours back found that my `projects.cson` became empty. This was not a big deal thanks to OSX Time Machine, but the situation is a bit alarming.

**Comment by danielbrodin** [comment] 2016-06-23 06:05
I haven't been able to reproduce this. Does everyone use Ubuntu?

**Comment by kachkaev** [comment] 2016-06-23 08:42
I was catching this both on Ubuntu and OSX

**Comment by ramirezd42** [comment] 2016-06-23 12:54
It's happening to me several times a day on OSX 10.11.5.

I have the following packages installed if that helps:

├── angularjs@0.3.4
├── atom-easy-jsdoc@4.6.0
├── atom-material-syntax@0.4.6
├── atom-material-syntax-dark@0.2.5
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.2.13
├── atom-typescript@8.11.0
├── atom-xcode@0.1.3
├── autocomplete-clang@0.9.3
├── autocomplete-haskell@0.6.5
├── build@0.64.0
├── build-xcodebuild@0.2.0
├── busy@0.5.0
├── change-case@0.6.0
├── clang-format@1.25.0
├── color-picker@2.1.1
├── docblockr@0.7.3
├── editorconfig@1.4.1
├── emmet@2.4.3
├── file-icons@1.7.15
├── git-plus@5.15.0
├── haskell-ghc-mod@1.14.6
├── jshint@1.8.5
├── language-cfml@0.13.0
├── language-docker@1.1.6
├── language-haskell@1.7.17
├── language-jsx@0.1.1
├── language-nginx@0.6.1
├── language-protobuf@0.5.0
├── linter@1.11.11
├── linter-clang@3.4.4
├── linter-eslint@7.2.4
├── linter-json-lint@0.1.1
├── linter-phpcs@1.4.0
├── linter-tslint@0.10.0
├── node-debugger@1.7.0
├── print-atom@0.1.1
├── project-manager@2.9.7
├── tabs-to-spaces@1.0.2
├── toggle-quotes@1.0.0
├── tree-view-copy-relative-path@1.0.0
└── vim-mode@0.65.1

**Comment by ramirezd42** [comment] 2016-06-27 17:25
I just uninstalled/re-installed the package, now everything works fine!

**Comment by danielbrodin** [comment] 2016-06-28 06:23
@ramirezd42 did you start over with your projects or copy/pasted from your old file?

Do all of you use templates?
Could anyone post their `projects.cson` content?

**Comment by jtinsky** [comment] 2016-07-04 21:41
No on templates. projects.cson file attached.
[projects.cson.zip](https://github.com/danielbrodin/atom-project-manager/files/346850/projects.cson.zip)

**Comment by danielbrodin** [comment] 2016-07-05 06:39
Is it on a certain project or any project?

**Comment by jtinsky** [comment] 2016-07-05 12:36
No particular project that I remember.

**Comment by tillkruss** [comment] 2016-08-13 18:45
This happened a coupled of time now. Super annoying...

**Comment by ramirezd42** [comment] 2016-08-13 18:49
I forgot to mention that this stopped happening for me after removing a project I had accidentally created that was pointing to my desktop. I wasn't able to reproduce it though by adding a new one from my desktop so I'm sure if that had something to do with it, or if it was just a coincidence. 

To those still experiencing this, I suggest removing projects from your ~/.atom/projects.cson file one at a time to see if one of them was problematic for whatever reason

**Comment by tillkruss** [comment] 2016-08-13 18:50
For me it seem to happen randomly every couple of days without any error message.

**Comment by crantila** [comment] 2016-08-31 02:27
> To those still experiencing this, I suggest removing projects from your ~/.atom/projects.cson file one at a time to see if one of them was problematic for whatever reason

One at a time, that's funny, because now they're *all* gone! I'm using Atom 1.9.8 on CentOS 7 with project-manager 2.9.7.

This has only happened to me twice, both within the past week, although I've been using project-manager almost since the Atom v1.0 release. Both times it happened when I just started Atom. I'd be happy to try out anything that might help narrow things down!

**Comment by rickmills** [comment] 2016-09-01 08:10
Had this happen yesterday. Came to start work this morning to find my entire projects list gone. Fixing this needs addressing with this as a matter of priority really.

(if it helps, OS X 10.11.5)

**Comment by danielbrodin** [comment] 2016-09-01 08:26
I still haven't been able to reproduce this, but I have an idea to where the problem could be, so I'm currently rewriting and restructuring the code to hopefully fix this issue.

**Comment by danielbrodin** [comment] 2016-09-01 13:24
So, I have pushed a "beta" branch that you can try if you want. I don't know of a way to automatically install it with atom or apm, so would have to install it manually by cloning the repo into your atom packages directory, switch to the beta branch and then do an `apm install` inside the repository. And also reload Atom since a lot of stuff have changed.

Please let me know if you try it and how it's working out for you.

**Comment by andresespinosapc** [comment] 2016-09-02 12:22
I had the same issue and my computer got frozen every time I opened Atom, having to shutdown with the power button! I fixed it by removing a missing directory from the projects.cson file.

**Comment by tillkruss** [comment] 2016-09-02 14:02
Thanks, @danielbrodin!

**Comment by danielbrodin** [comment] 2016-09-02 14:52
@tillkruss Something to note about the beta branch is that there are some things I'm testing in it, like adding more fields to the save project window, and with a setting you can also include git repositories inside your `core.projectHome` directory, and these things could be a bit sloppy just because I'm testing things out.

So please let me know about bugs, and if it works out for you.

Also, the `projects.cson` structure have been changed (it will change the first time you do a save) + it now always contain all options available

**Comment by Toub** [comment] 2016-10-17 08:34
Just reproduced today. Very annoying!

I am not sure, but it could be due to the fact I pressed <alt>+<shift>+P immediately after the UI appears (and probably before everything has been loaded).

**Comment by crantila** [comment] 2016-10-18 00:44
@Toub are you using the msot recent release? I can't reproduce the problem any more after @danielbrodin kindly published several updates!

**Comment by Toub** [comment] 2016-10-18 06:48
Sorry, I forgot to mention the version.

I was atom 1.10, but I am not sure about the plugin's version because I upgraded everything (atom+plugins) just after the bug occurred.

I wil let you know if it appends again.

Thanks for the fix, I didn't know it was already released.

**Closed** 2019-09-19 14:38 UTC
